apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  - generictopologyprocessor-deployment.yaml
  - generictopologyprocessor-service.yaml
  - generictopologyprocessor-serviceaccount.yaml
  - generictopologyprocessor-observerrole.yaml
  - generictopologyprocessor-observerrolebinding.yaml
  - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: java-grpc-connector-template
    newName: docker.io/cookcm/sample-java-template
    newTag: latest
  - name: generic-topology-processor
    newName: cp.icr.io/cp/cp4waiops/generic-topology-processor
    digest: sha256:a25bdeb0a8beae638173b28b69daa6cddbfa8dd6cce36853d069f36b057a43e9